### ISSUE TITLE
PhrasePhreak 0.1 incompatible with Renoise 3.1

### ISSUE THREAD

**Issue by hced** [patmaddox/renoise-tools#1]
Hi,

When enabling PhrasePhreak 0.1 in Renoise 3.1 it give the following error and gets disabled:

`ScriptingTools: Script with the ID 'com.patmaddox.PhrasePhreak' is NOT compatible and can't be auto-upgraded because of token(s) 'can_insert_phrase_at, insert_phrase_at'. Disabling the tool...`

PS. Since I'm new to Renoise I don't know if the Selection/Column/Track operation, `Create Phrase`, makes PhrasePhreak redundant? DS.

**Comment by patmaddox** [comment]
Yeah, soon after I wrote PhrasePhreak they updated Renoise and changed the phrase API. I haven't had a chance to look into it since.

Renoise's built-in `Create Phrase` has an important limitation – it can only create one phrase, it can't add phrases to an instrument that already has phrases.

**Check out [PhraseMate](https://www.renoise.com/tools/phrasemate) for an awesome tool for working with phrases.**

----

Note: I'm closing this issue since I don't plan to fix it any time soon. Please feel free to email me again if PhraseMate doesn't do what you want, or we can talk about it on the [forum thread](http://forum.renoise.com/index.php/topic/46284-new-tool-31-phrasemate/).
